language: android
dist: trusty
sudo: false
jdk:
- oraclejdk8
android:
  components:
  - tools
  - android-26
  - build-tools-26.0.2
  - platform-tools
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- cp -v sample_config_files/sample_keystore.properties keystore.properties
- keytool -genkeypair -dname "cn=TravisCI, ou=TravisCI, o=Sun, c=US" -alias business
  -keypass kpi135 -keystore android.keystore -storepass ab987c -validity 20000
after_success:
- bash scripts/update_apk.sh
branches:
  only:
  - master
  - development
env:
  global:
    secure: oN3Qv2o4/6+ynHSEMSrRd2FHbVHCt2V6r9guE+bdvfwzk7EtkXAeSoi2aYscrkwhw+dMj7y+ZFYofdZHIVJarX4ehswVmhhL7fjx/LcBqglHeNtaBzQqtAviPHeOt9C0016QncFJMTaa7J+Hch7tXhqT2wz8iv2NRzb9VBa2W/PANdwpf6DmrBnlpIiwJR2OQDFKsWOiY7/AeWjDTSoIfHnd92OkidV1TkdzwqZeQCfXCLk6SoLOwPn2uQR6QmXginPo29cX9lzpUiPY+hyk8bLoz9O+D+exfMthyt2K92BfiiXMsrboPjjS8PioOH6yDFJ8t0aZQYz87XPUn5TFGlEvODijhGC2zX/zX5qtvLxASxfeTin10N7P44NxhSFQ0fUY7oyeSBfb6uQU8CjKV9QNZn//THqqVmCn2ZPfLModfgiznseXu1X6ysXoAhY5FmLQRakyANrwoEyRnau/8d6U3Hk+EEYVprPwzGkf7iPonYNRqr1BdwfQXVAjjTQoagwBE+hkg9aF/0OWxNkoy+kY2K1/Md2260KfwlfpvfSQROs5niOa1CWAwMuh6LeoPIIiKFVswBHrqPi/Dm40oXCNsZvX7hJF/UDrrD2E6uCvL1RsYYzxdtZa4az+/2W+E5Yo+KhcqVgiFC7s7nldPnpJuct0jqLV5KoMw0QcGWA=
